version: '3.4'

services:
  release:
    image: tons/oneliners-web:${TAG}
    build: .
    environment:
      ONELINERS_API: ${BACKEND}
    ports:
      - 80:80

  dev:
    image: node:alpine
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'npm install && exec npm run dev'
    depends_on:
      - api
    ports:
      - 80:8080
    environment:
      HOST: 0.0.0.0
# TODO:
#      ONELINERS_API: ${BACKEND}

  api:
    image: tons/oneliner-backend
    depends_on:
     - database
    ports:
     - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
     # The entire url should probably be passed and not just the database name... or not, jdbc, postgresql and the port(?) are static and wont change
      DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_DATABASE}
      DATASOURCE_USERNAME: ${DB_USERNAME}
      DATASOURCE_PASSWORD: ${DB_PASSWORD}

  database:
    image: postgres:10-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}

volumes:
  database: {}
